using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Tama : MonoBehaviour
{
    public GameObject tama;//’e‚ğŠi”[‚·‚é•Ï”
    public GameObject teki;//“G‚ğŠi”[‚·‚é•Ï”
    public float timeOut;//¶¬ŠÔŠu‚ğŠi”[‚·‚é•Ï”
    private float timeElapsed;//Œo‰ßŠÔ‚ğŠi”[‚·‚é•Ï”
    private EnemyStart enemyStart;//EnemyStart‚ğŠi”[‚·‚é•Ï”

    void Update()
    {
        enemyStart = FindObjectOfType<EnemyStart>();//EnemyStart‚Ìî•ñ‚ğæ“¾
        if (enemyStart.Go == 1)//ƒXƒ^[ƒgƒ{ƒ^ƒ“‚ª‰Ÿ‚³‚ê‚½‚çÀs
        {
            timeElapsed += Time.deltaTime;//Œo‰ßŠÔ‚ğ‘ª’è
            if (timeElapsed >= timeOut)//Œo‰ßŠÔ‚ªtimeOut‚É’B‚µ‚½‚çÀs
            {
                GameObject gameObject = Instantiate(tama, transform.position, transform.rotation);//’e‚ğ¶¬
                TaihouController taihouController = GetComponent<TaihouController>();//taihouController‚Ìî•ñ‚ğæ“¾
                Idou idou = gameObject.GetComponent<Idou>();//Idou‚Ìî•ñ‚ğæ“¾
                idou.damage = taihouController.dmg;//ƒ_ƒ[ƒWî•ñ‚ğIdou‚É“`‚¦‚é
                timeElapsed = 0.0f;//Œo‰ßŠÔƒŠƒZƒbƒg
            }
        }
    }
}
